identifier:
  image: semtech/mu-identifier
  links:
    - dispatcher:dispatcher
  ports:
    - "8011:80"
dispatcher:
  image: semtech/mu-dispatcher
  links:
    - resource:resource
  volumes:
    - ./config/dispatcher:/config
rewriter:
  image: bde2020/mu-query-rewriter
  extra_hosts:
   - "database:localhost"
  environment:
    REWRITE_SELECT_QUERIES: "true"
    PLUGIN: "uuids"
    DEBUG_LOGGING: "true"
    MESSAGE_LOGGING: "true"
  volumes:
    - ./config/rewriter:/config
    - ./config/resources:/resources
  ports:
    - "4027:8890"
resource:
  image: nathanielrb/mu-cl-resources
  links:
    - rewriter:database
  volumes:
    - ./config/resources:/config
  ports:
    - "8082:80"
    - "4006:4005"
  environment:
    MU_APPLICATION_GRAPH: "http://yourdatastories.eu/test"
    MU_DECLARE_RESOURCE_TYPES: "true"
oldresource:
  image: nathanielrb/mu-cl-resources
  extra_hosts:
   - "database:localhost"
  volumes:
    - ./config/resources:/config
  ports:
    - "8083:80"
  environment:
    MU_APPLICATION_GRAPH: "http://yourdatastories.eu/test"
