identifier:
  image: semtech/mu-identifier
  links:
    - dispatcher:dispatcher
  ports:
    - "80:80"
dispatcher:
  image: semtech/mu-dispatcher
  links:
    - resource:resource
  volumes:
    - ./config/dispatcher:/config
db:
  image: tenforce/virtuoso:virtuoso-v7.2.0-latest
  volumes:
    - ./data/db:/var/lib/virtuoso/db
  environment:
    SPARQL_UPDATE: "true"
  ports:
    - "8890:8890"
resource:
  image: semtech/mu-cl-resources
  links:
    - db:database
  volumes:
    - ./config/resources:/config
  environment:
    BOOT: mu-cl-resources
  ports:
    - "8082:80"
    - "4006:4005"
